on: [push, pull_request]

name: Build

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build smbclient

    strategy:
      fail-fast: false
      matrix:
        pkgver:
          - 4.15.1
          - 4.14.9
          - 4.13.12
          - 4.12.15
          - 4.11.17
          - 4.10.18
          - 4.9.18
          - 4.8.12
          - 4.7.12

    steps:
      - name: Install build dependencies
        run: |
          sudo sed -Ei '/.*partner/! s/^# (deb-src .*)/\1/g' /etc/apt/sources.list
          sudo apt update
          sudo apt-get build-dep smbclient
      - name: Download sources
        run: |
          wget "https://download.samba.org/pub/samba/stable/samba-${{ matrix.pkgver }}.tar.gz"
          tar xf samba-${{ matrix.pkgver }}.tar.gz
      - name: Build smbclient
        run: |
          cd samba-${{ matrix.pkgver }}
          ./buildtools/bin/waf configure --prefix= --bundled-libraries=ALL --with-static-modules=ALL --nonshared-binary=client/smbclient --without-ad-dc --without-gettext --with-winbind --without-ads --disable-cups --without-json --without-ldap --without-libarchive --without-pam
          ./buildtools/bin/waf build -j $(nproc --all) --targets client/smbclient
      - name: Upload binaries to release
        uses: actions/upload-artifact@v2
        with:
          path: samba-${{ matrix.pkgver }}/bin/default/source3/client/smbclient
          name: smbclient-${{ matrix.pkgver }}
