on: [push, pull_request]

name: Build

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build smbclient

    strategy:
      fail-fast: false
      matrix:
        pkgver:
          - 4.18.1
          - 4.17.7
          - 4.16.10
          - 4.15.13
          - 4.14.9
          - 4.13.12
          - 4.12.15
          - 4.11.17
          - 4.10.18
          - 4.9.18
          - 4.8.12
          - 4.7.12
          - 4.6.16
          - 4.5.16
          - 4.4.16
          - 4.3.13
          - 4.2.14

    steps:
      - uses: actions/checkout@v2
      - name: Install build dependencies
        run: |
          sudo sed -Ei '/.*partner/! s/^# (deb-src .*)/\1/g' /etc/apt/sources.list
          sudo apt update
          sudo apt-get build-dep smbclient
          sudo apt install python2.7-dev
      - name: Download sources
        run: |
          wget -q "https://download.samba.org/pub/samba/stable/samba-${{ matrix.pkgver }}.tar.gz"
          tar xf samba-${{ matrix.pkgver }}.tar.gz
      - name: Switch to python 2.7 for <=4.9
        if: matrix.pkgver == '4.9.18' || matrix.pkgver == '4.8.12' || matrix.pkgver == '4.7.12' || matrix.pkgver == '4.6.16' || matrix.pkgver == '4.5.16' || matrix.pkgver == '4.4.16' || matrix.pkgver == '4.3.13' || matrix.pkgver == '4.2.14'
        run: |
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1
      - name: Patch for <=4.3
        if: matrix.pkgver == '4.3.13' || matrix.pkgver == '4.2.14'
        run: |
          cd samba-${{ matrix.pkgver }}
          patch -p1 < ../perl_inc.patch
      - name: Configure
        run: |
          cd samba-${{ matrix.pkgver }}
          ./buildtools/bin/waf configure --prefix=/usr --bundled-libraries=ALL --with-static-modules=ALL --nonshared-binary=client/smbclient \
              --without-ad-dc --without-gettext --with-winbind --without-ads --disable-cups --without-ldap --without-libarchive --without-pam \
              --with-configdir=/etc/samba --sysconfdir=/etc/samba --localstatedir=/var --enable-fhs
      - name: Build
        run: |
          cd samba-${{ matrix.pkgver }}
          ./buildtools/bin/waf build -j $(nproc --all) --targets client/smbclient
      - name: Upload binaries to release
        uses: actions/upload-artifact@v2
        with:
          path: samba-${{ matrix.pkgver }}/bin/default/source3/client/smbclient
          name: smbclient-${{ matrix.pkgver }}
